x-veld:
  code:

services:
  veld_udpipe_2_infer_direct:
    build:
      context: .
      dockerfile: udpipe_2.dockerfile
    command: python udpipe2_direct.py /veld/input/model/udpipe2-ud-2.10-220711/de_hdt-ud-2.10-220711.model/ de_hdt
    volumes:
      - ./data/inference/input/txt/:/veld/input/txt/
      - ./data/inference/input/model/:/veld/input/model/
      - ./data/inference/output/:/veld/output/
      - ./src/udpipe_2/:/veld/code/
      - ./data/cache/nv/:/root/.nv/ComputeCache
      - ./data/cache/hf/:/root/.cache/huggingface/
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

